# Generated by Django 2.1.4 on 2018-12-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Gönderilerim'},
        ),
    ]
