# Generated by Django 2.1.4 on 2018-12-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181227_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
    ]
