# Generated by Django 2.1.4 on 2018-12-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20181227_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='Resim Dosyası Yükleyebilirsiniz', upload_to='', verbose_name='Post Resim'),
        ),
    ]
