# Generated by Django 2.1.4 on 2018-12-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20181229_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='Resim Dosyası Yükleyebilirsiniz', upload_to='upload_to', verbose_name='Fotoğraf'),
        ),
    ]
