# Generated by Django 2.1.4 on 2018-12-28 21:56

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20181229_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='Resim Dosyası Yükleyebilirsiniz', upload_to=post.models.upload_to, verbose_name='Fotoğraf'),
        ),
    ]
