# Generated by Django 2.1.4 on 2018-12-29 00:00

import ckeditor.fields
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20181229_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='(Kategori seçimi yapınız)', related_name='post', to='post.Category', verbose_name='Kategoriler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='(İçerik giriniz)', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='(Resim Dosyası Yükleyebilirsiniz)', upload_to=post.models.upload_to, verbose_name='Fotoğraf'),
        ),
    ]
