# Generated by Django 2.1.4 on 2018-12-29 00:02

import ckeditor.fields
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20181229_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to=post.models.upload_to, verbose_name='Fotoğraf'),
        ),
    ]
