# Generated by Django 2.1.4 on 2019-01-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20190113_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time'], 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
