# Generated by Django 2.1.4 on 2019-01-13 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Telefon Numarası')),
                ('sex', models.CharField(blank=True, default=3, max_length=1, verbose_name='Cinsiyet')),
                ('biography', models.TextField(blank=True, max_length=500, verbose_name='Hakkında')),
                ('birth_date', models.DateField(blank=True, verbose_name='Doğum Tarihi')),
                ('profile_photo', models.ImageField(blank=True, upload_to=user.models.upload_to, verbose_name='Profil Fotoğrafı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı Bilgileri',
            },
        ),
    ]
