# Generated by Django 2.1.4 on 2019-01-14 15:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190113_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=user.models.upload_to, verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın'), ('O', 'Diğer')], default=3, max_length=1, verbose_name='Cinsiyet'),
        ),
    ]
