# Generated by Django 2.1.4 on 2019-01-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190114_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('O', 'Diğer'), ('K', 'Kadın'), ('E', 'Erkek')], default=3, max_length=1, verbose_name='Cinsiyet'),
        ),
    ]
