# Generated by Django 2.1.4 on 2019-01-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190117_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın'), ('O', 'Diğer')], default=3, max_length=1, verbose_name='asdasf'),
        ),
    ]
