# Generated by Django 2.1.4 on 2019-01-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190117_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, max_length=500, verbose_name='Hakkımda'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('K', 'Kadın'), ('E', 'Erkek'), ('O', 'Diğer')], default=3, max_length=1, verbose_name='Cinsiyeti'),
        ),
    ]
