# Generated by Django 2.1.4 on 2019-01-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190117_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('K', 'Kadın'), ('O', 'Diğer'), ('E', 'Erkek')], default=3, max_length=1, verbose_name='Cinsiyet'),
        ),
    ]
