# Generated by Django 2.1.7 on 2019-03-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20190304_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('K', 'Kadın'), ('E', 'Erkek'), ('O', 'Diğer')], default=3, max_length=1, verbose_name='Cinsiyet'),
        ),
    ]
